### PR TITLE
Created custom gif for 404 and created the 404 page

### PR DESCRIPTION
**Pull request by FireQueen-3010**
1) Created a transparent custom animated gif:

Square Video Post 1080x1080 px (3)

Square-Video-Post-1080x1080-px-unscreen (3)
3) Added 404 page and made it mobile responsive:

image

image

https://user-images.githubusercontent.com/59244300/114278824-2ba10980-9a4f-11eb-831f-c7f21abe8678.mp4

### CODE REVIEW

**Comment by FireQueen-3010** [comment]
Please review @ArunTeltia @LordShenron :)

**Review by LordShenron — APPROVED** [review]
Damn xD, thumbs up to this

**Comment by FireQueen-3010** [comment]
Tnx :) also, Arun said you need to merge it 😅

**Comment by LordShenron** [comment]
> Tnx :) also, Arun said you need to merge it sweat_smile @LordShenron

Yeah.. i will do it later coz working on rom sources rn

**Comment by FireQueen-3010** [comment]
Yeah okay, even the loader pr! :)

**Pull request merged**
