### PR TITLE
Added responsiveness to the apply page

### PR DESCRIPTION
**Pull request by ritik307**
**Description**
The website is now responsive to different viewports.

Fixes: #27 

**Screenshots**
res-fix

### CODE REVIEW

**Comment by ritik307** [comment]
@LordShenron @ArunTeltia Plz review

**Comment by ArunTeltia** [comment]
can you share the image tho it is looking good to me @LordShenron can we merge this

**Comment by ArunTeltia** [comment]
great catch i am  bumping up the level for this one

**Comment by ritik307** [comment]
@ArunTeltia it is shown in issue #27

**Comment by ArunTeltia** [comment]
okay merge it @LordShenron 
Thanks @ritik307 for this one

**Pull request merged**
