### PR TITLE
Added animated loader while switching between components

### PR DESCRIPTION
**Pull request by FireQueen-3010**
Setimeout to 1.5 s :
https://user-images.githubusercontent.com/59244300/114163244-9535f080-9947-11eb-89ea-926d02ebba02.mp4

### CODE REVIEW

**Comment by FireQueen-3010** [comment]
Please review @ArunTeltia :)

**Comment by ArunTeltia** [comment]
I am sorry @FireQueen-3010 but we are not thinking of using bootstrap library in the project can we check something out with the help of material ui,

**Comment by ArunTeltia** [comment]
plus instead of copy pasting it to every element can we just create another component for and then can reference that component
Basically writing a DRY code

**Comment by FireQueen-3010** [comment]
> I am sorry @FireQueen-3010 but we are not thinking of using bootstrap library in the project can we check something out with the help of material ui,

Yeah actually I haven't used bootstrap. I was experimenting so had to install bootstrap for that but forgot to remove it and sry abt that. I've used material UI itself. :) @ArunTeltia

**Comment by FireQueen-3010** [comment]
> plus instead of copy pasting it to every element can we just create another component for and then can reference that component
> Basically writing a DRY code

Okay.. actually it applies to every page so thought I need to add the hooks to each page. I'll try to make it as DRY as possible. Thank you :) @ArunTeltia

**Comment by FireQueen-3010** [comment]
Removed boostrap :)

**Comment by ArunTeltia** [comment]
Looks good to me @LordShenron Please merge

**Pull request merged**
