### PR TITLE
Added footer and  MIT license

### PR DESCRIPTION
**Pull request by FireQueen-3010**
Issue : #8

Desk-view:
image
Mobile-view:
image

### CODE REVIEW

**Comment by FireQueen-3010** [comment]
Please review @ArunTeltia @LordShenron :)

**Comment by LordShenron** [comment]
Don't you feel in mobile view it look a bit weird. It should be complete end to end.

**Comment by FireQueen-3010** [comment]
Please check now, I tested by putting border around :
image

**Comment by ArunTeltia** [comment]
LOOKS GOOD TO ME

**Review by ArunTeltia — APPROVED** [review]

**Comment by FireQueen-3010** [comment]
Could you pls add labels 😅 @ArunTeltia @LordShenron

**Pull request merged**
